language: cpp

compiler: gcc

notifications:
  email: false
  
addons:
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - gcc-4.8
  
script: gcc -std=c++11 -o chess *.cpp figures/*.cpp
